### ISSUE TITLE
Requests > add filter to order requests by date/status

### ISSUE THREAD

**Issue by sponzillo** [chat21/chat21-support-dashboard#5]

**Comment by nicolan74** [comment]
due to this issue: "You have a where filter with an inequality (<, <=, >, or >=) on field 'support_status' and so you must also use 'support_status' as your first Query.orderBy(), but your first Query.orderBy() is on field 'timestamp' instead.";
i have simply did ref.where('support_status', '<', 1000).orderBy('support_status').orderBy('timestamp', 'desc'));
